### ISSUE TITLE
Icon change discuss

### ISSUE THREAD

**Issue by xrkffgg** [canary-js/icon#1]
### Old

![canary](https://user-images.githubusercontent.com/29775873/93965952-fcb69500-fd95-11ea-9768-833d87ae8979.png)

### New 1

![2128936](https://user-images.githubusercontent.com/29775873/93967180-3341df00-fd99-11ea-9637-71403dea9893.png)

### New 2
![canary (1)](https://user-images.githubusercontent.com/29775873/93967204-481e7280-fd99-11ea-926b-33a7968755f7.png)

### New 3

![canary (2)](https://user-images.githubusercontent.com/29775873/93967212-4e145380-fd99-11ea-8884-242a4ba6799d.png)

### New 4

![canary (3)](https://user-images.githubusercontent.com/29775873/93967223-540a3480-fd99-11ea-90b1-49e5306ef122.png)

**Comment by xrkffgg** [comment]
@willin 

感觉原来的不是很好，新选了几个，你看看，有啥钟意的？或者有新的？

**Comment by xrkffgg** [comment]
cc @willin

**Comment by willin** [comment]
prefer 3
